### ISSUE TITLE
unable to create DB revision with clean DB

### ISSUE THREAD

**Issue by mdvz0r** [workfloworchestrator/orchestrator-core#121]
steps to reproduce:

- spin up an empty DB
- use basic example script from repo to init DB: `PYTHONPATH=. python main.py db init`
- and use this script to run migrations: `PYTHONPATH=. python main.py db upgrade heads`
- now try to create a simple migration: `PYTHONPATH=. python main.py db revision --message "simple migration" --head=data@head`

This last step should result in an available migration file, but will result in `alembic.util.exc.CommandError: Can't locate revision identified by 'data'`.

**Comment by acidjunk** [comment]
I think in the core data/schema are mixed.
