### ISSUE TITLE
[Feature Request] Unified auth mechanism and/or authentication docs

### ISSUE THREAD

**Issue by gstewart86** [workfloworchestrator/orchestrator-core#133]
Good Morning,

When implementing auth in our version of the Orchestrator, we had to put a custom authentication function in `/esnetorch.identity`, and then implement the follow elements to properly enable authentication:

/monkeypatch.py
```
...
from esnetorch.identity.controller import oidc_security

...
class EsnetWebsocketManager(orchestrator.websocket.WebSocketManager):
    async def authorize(self, websocket: WebSocket, token: str) -> Optional[Dict]:
        try:
            await oidc_security(request=websocket, token=token)
        except HTTPException as e:
            return {"error": vars(e)}
        return None


orchestrator.websocket.WebSocketManager = EsnetWebsocketManager
```

/main.py
```
import monkeypatch
```

/esnetorch/__init__.py
```
def load_esnet(app: OrchestratorCore) -> None:
...

    app.dependency_overrides[opa_security_default] = oidc_security
    app.dependency_overrides[oidc_user] = oidc_security
```

/esnetorch/api/api_v1/api.py
```
api_router = APIRouter()

api_router.include_router(esdb.router, prefix="/api", dependencies=[Depends(oidc_security)])
```

I get the sense that the last two entries are the 'normal' ways to wire up auth to a route, but it would be nice if there was documentation around a recommend auth mechanism or a unified way to implement this kind of thing.

**Comment by pboers1988** [comment]
@gstewart86 @acidjunk Perhaps we should dicuss this in the following meeting, however as far as I can see we are willing to provide feedback on any contribution that would make the current way of working with auth configurable. As long as the method results in a dependancy that can be injected at the endpoint level to do Authz we should be able to make it configurable/pluggable into the main `OrchestratorCore` class. I.E if we can override the `opa_decision` function at startup with a custom function. We are golden. Then each and every person can configure their own Authz.

**Comment by pboers1988** [comment]
Closing, stale
