### ISSUE TITLE
Recursively gather child subscriptions?

### ISSUE THREAD

**Issue by gstewart86** [workfloworchestrator/orchestrator-core#139]
Before I try to write this myself, Is there a built-in function to generate a data structure containing recursive children (depends_on?) subscriptions?

For example, I'd like to recursively modify the state of all BGP Peer subscriptions present on a Device, where the tree looks something like:
```
   Device
    │
    └─Port
       │
       └─Logical Interface
          │
          └─BGPPeer
```

so I would need something like 
```
depends_on_tree = get_child_subscriptions(recursive=True)
```

**Comment by gstewart86** [comment]
This is great thank you for the information!

**Comment by gstewart86** [comment]
@pboers1988 Based on our conversation last week, I figured I would just reopen this issue. During the meeting, you showed the ability to conditionally execute a set of steps using a `focussteps` function, like so:

```
@modify_workflow
def modify() -> StepList:
    def _has_state_key(state_var: str) -> Callable:
        return conditional(lambda state: state_var in state and state[state_var])

    with_fw_subscription = focussteps("fw_state")

    return (
        begin
...
        >> _has_state_key("fw_state")(with_fw_subscription(re_deploy_fw_nfv()))
```

This kind of thing sounds like it might allow us to modify child subscriptions in a way that preserves the Subscription Boundary™. Would you mind sharing a bit of the `re_deploy_fw_nfv` as well? Is that just a StepList? Does it also have a workflow type decorator?

**Comment by pboers1988** [comment]
@gstewart86 the `re_deploy_fw_nfv` is just a steplist (ie an @workflow decorated function). It gets passed the contents of the key  `fw_state`. The contents of the key in the state is arbitratry and your choice, it basically executes a new workflow where the root state of that workflow is the contents of `fw_state`

Does that answer you question?

**Comment by gstewart86** [comment]
It does, thank you!
