### ISSUE TITLE
Update workshop for orchestrator-core 1.x

### ISSUE THREAD

**Issue by Mark90** [workfloworchestrator/orchestrator-core#232]
https://github.com/workfloworchestrator/orchestrator-core/blob/74c66cf79c29f7a8a7395dd87bf1606cea924440/docs/workshops/beginner/debian.md

As of orchestrator-core the minimum Python version is 3.10, which also means Debian 11 doesn't have the required version of Python.

**Comment by hanstrompert** [comment]
Maybe use another Python virtual environment tool that can easily install different Python versions?  For example pyenv, see https://github.com/pyenv/pyenv-installer, you only need to install the distribution specific build dependencies, and then you can just say `pyenv install 3.10.9`.

**Comment by Mark90** [comment]
see #241
