### ISSUE TITLE
Make sure you cannot restart/resume workflows/tasks twice

### ISSUE THREAD

**Issue by hanstrompert** [workfloworchestrator/orchestrator-core#242]
### Summary

At this point in time it is possible to retry a workflow or task twice on the celery bus. Make sure it is not possible to do this by implementing a new ProcessStatus state RESUMED. Then a workflow/task will transition from CREATED to RUNNING to either DONE, SUSPENDED or FAILED, a SUSPENDED or FAILED workflow/task can be resumed or restarted and will transition to RESUMED.

### Solution

* [ ]  implement a new ProcessStatus RESUMED
* [ ]  add logic to prohibit a already restarted/resumed workflow to be restarted/resumed again

**Comment by coleshaw** [comment]
@hanstrompert , can I make sure I understand the issue?

Does the current workflow have a race condition, where a `SUSPENDED` or `FAILED` task can be re-started, which puts it into the Celery queue. But, before a Celery worker picks up the task (and it would change to `RUNNING` status), it is possible for a user or other process to see the task as still `SUSPENDED` / `FAILED`, and put it back onto the Celery queue, so the task is duplicated on the queue?

And the idea would be to change the workflow to:

`SUSPENDED` -> user restarts -> task put on Celery queue and changed to `RESUMED` -> user cannot restart task -> Celery worker picks up the tasks and state changes to `RUNNING`

?

And thus `RESUMED` indicates that a process has been put onto the Celery queue but has not been picked up yet by a worker, and this implies that it cannot be restarted again.

Thanks!

**Comment by hanstrompert** [comment]
Hi @coleshaw, thank you for the detailed description, that is exactly the problem, and the solution!
