### ISSUE TITLE
Support for adding generic metadata to subscriptions

### ISSUE THREAD

**Issue by dmarjenburgh** [workfloworchestrator/orchestrator-core#266]
## Feature description 

This feature allows workfloworchestrator developers to add various kinds of metadata to subscriptions in their workflows. The goal is to support metadata for subscriptions in a way that doesn't require custom database schema changes. It can be viewed as an extension of the *note* field that is present on subscriptions currently. The supported metadata should be semi-static (slow-changing) and flexible.

### Rationale

There have been a number of use-cases where more data needs to be attached to subscriptions than is currently supported out-of-the-box. The type of data varies per domain and use-case, but some examples could be:

- External references (like 3rd-part ids)
- Free text descriptions
- Location / contact information

By supporting flexible metadata objects to subscriptions, less custom work is required by workfloworchestrator developers to support their use-case.

### Design and implementation

We propose to add a `subscription_metadata` table with the following schema:

| column_name | type |
|--------|--------|
| subscription_id | UUID (references subscription)|
| metadata | JSON | 

The table contents can be managed by custom workflows with a JSON schema that match the required use-case. An basic endpoint will be available at `GET api/subscriptions/{subscription_id}/metadata` that returns the requested metadata in a JSON response.
**Optional:** The endpoint can be extended to accept a URI-encoded JSONPath filter in a query parameter.

Tasks:

- [ ] Add db migration to create the subscription_metadata table
- [ ] Define SQLAlchemy objects for interacting with the metadata
- [ ] Implement api endpoint for querying the metadata

Optional or future tasks:

- [ ] Migrate existing subscription note to the generic metadata object
- [ ] Add filter options to subscription metadata endpoint (e.g. a `filter` query-param with a URI-encoded JSONPath string)
- [ ] Migrate subscription_customer_descriptions to the generic metadata object

**Comment by acidjunk** [comment]
We discussed using this in the frontend, this afternoon: it would be nice to know the types. Maybe good to consider using JSON scheme

https://json-schema.org/specification.html

**Comment by hanstrompert** [comment]
Good suggestion. We will revisit this issue after an initial implementation of the metadata endpoint. For now the GUI will just display all metadata as strings without any type specific processing.
