### ISSUE TITLE
orchestrator-core Improvements to migrate-workflows wizard

### ISSUE THREAD

**Issue by hanstrompert** [workfloworchestrator/orchestrator-core#281]
### Problem to solve

When there are a lot of workflows and product_types, the current selection menu is a bit unwieldy. In other words, the list of workflows can become very long.

### Intended users
All workfloworchestrator custom implementation developers.

### Proposal

- When selecting a workflow to create. Separate the workflows into the ones missing in the db and already present in the db.
- Possibility to delete multiple workflows by entering a comma-separated list

### Tasks

- [ ]  extra step to separate by lifecycle state
- [ ]  add **(new)** after not already linked workflows

**Comment by pboers1988** [comment]
Most users have migrated, closing.
