### ISSUE TITLE
Investigate "Created" state when using Celery

### ISSUE THREAD

**Issue by pboers1988** [workfloworchestrator/orchestrator-core#292]
When using the celery worker, and a process is put on the queue, it gets set to the status "created", however when all containers or processes are restarted, the workers do not pickup "created" tasks. Please investigate and come up with a solution. There probably is an issue with how the queue is set up.

**Comment by tjeerddie** [comment]
I can't seem to reproduce this, we should investigate if this happens again

**Comment by pboers1988** [comment]
If it cannot be reproduced I'll close the issue.
