### ISSUE TITLE
Introducing @async_step for Improved Asynchronous Task Management and User Confirmation

### ISSUE THREAD

**Issue by torkashvand** [workfloworchestrator/orchestrator-core#359]
In one of our workflow steps, we initiate an asynchronous call to an external service. 
Due to the time-consuming nature of this service, instead of returning the actual result immediately, it provides us with a `job_id`. 
As we wait for this result, we advance the user to the next step. Currently, we're in the dark, with no indication of when the actual result will be available, leading us to rely on manual GUI refreshes, which is far from ideal.

Note: The asynchronous call is for a DRY run on the remote device (router or switch). It's imperative that once the result of this long-running task is available, it MUST be presented to the user for confirmation in a separate step before any real changes can be made.

We attempted to use the **`@inputstep`**, but it doesn't fit our needs. As documentation explicitly mentions that the **`@inputstep`** wrapped function should not run in the workflow engine and should avoid making database or external system changes.

To better handle this scenario, we propose the introduction of a feature like **`@async_step`** that would:

- Initiate the asynchronous service call.
- Wait and automatically check for the run result, irrespective of whether it's pulling or pushing.
- Present the result to the user for confirmation in a separate step if it's necessary.
- Continue with the subsequent steps in the workflow post-confirmation.

The **`@async_step`** feature would significantly enhance our ability to manage asynchronous operations that necessitate user confirmations within workflow-orchestrator-core

Thank you in advance for your assistance.

**Comment by Mark90** [comment]
@dmarjenburgh has recently added a `step_group` in #343 and on top of that built a `@callback_step` in #354. This provides better handling of async calls to external systems (new process state 'awaiting callback', validating the result from the external system, retry the call on specific conditions). 

This should cover most of your needs - although if you want a user to confirm the input, I don't think it can retry the call to the external system (I could be wrong though)

It's finished, but we aren't using it ourselves yet and there is no documentation yet as far as I can tell.
But the unittests and PR details should give some idea of what it can do.

**Comment by torkashvand** [comment]
Thanks, @Mark90. However, the @callback_step is in the main branch and hasn't been packaged yet.

**Comment by pboers1988** [comment]
Closing as it already is implemented. It will be release soon.

**Comment by pboers1988** [comment]
@torkashvand This feature has been released in 1.3.1
