### ISSUE TITLE
unnecessary json.loads in continue_awaiting_process_endpoint

### ISSUE THREAD

**Issue by torkashvand** [workfloworchestrator/orchestrator-core#360]
Hi considering this code

```python 
@router.post(
    "/{process_id}/callback/{token}",
    response_model=None,
    status_code=HTTPStatus.OK,
    dependencies=[Depends(check_global_lock, use_cache=False)],
)
def continue_awaiting_process_endpoint(
    process_id: UUID,
    token: str,
    request: Request,
    json_data: JSON = Body(...),
) -> None:
    check_global_lock()

    process = _get_process(process_id)

    if process.last_status != ProcessStatus.AWAITING_CALLBACK:
        raise_status(HTTPStatus.CONFLICT, "This process is not in an awaiting state.")

    try:
        continue_awaiting_process(process, token=token, input_data=json.loads(json_data))
    except AssertionError as e:
        raise_status(HTTPStatus.NOT_FOUND, str(e))
```
        

The `json_data: JSON = Body(...)`  line in this function argument already instructs FastAPI to take the JSON content from the request body and convert it into the appropriate Python type. Therefore, you can use json_data directly in your function as a Python object without the need for `json.loads.`
     
I wanted to create a PR but I couldn't. I might do something wrong!

**Comment by tjeerddie** [comment]
good spot and you should be able to create a PR from a fork of the project

**Comment by torkashvand** [comment]
Created a [PR](https://github.com/workfloworchestrator/orchestrator-core/pull/361)

**Comment by pboers1988** [comment]
PR merged
