### ISSUE TITLE
Update SQLAlchemy queries from v1 to v2 

### ISSUE THREAD

**Issue by tjeerddie** [workfloworchestrator/orchestrator-core#386]
Changing the `Table.query` queries to use `select(Table)`

- [ ] orchestrator.api folder
- [ ] orchestrator.cli folder
- [ ] orchestrator.db folder
  - [ ] models
  - [x] sorting
  - [x] filters
- [ ] orchestrator.domain.base
- [x] orchestrator.graphql folder
- [ ] orchestrator.services folder
- [ ] orchestrator.schedules folder
- [ ] orchestrator.workflows folder

**Comment by Mark90** [comment]
@tjeerddie can we close this?

**Comment by Mark90** [comment]
Not done yet, still getting a lot of these warnings in the unittests;

> LegacyAPIWarning: The Query.get() method is considered legacy as of the 1.x series of SQLAlchemy and becomes a legacy construct in 2.0. The method is now available as Session.get() (deprecated since: 2.0) (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)

>  LegacyAPIWarning: The Query.with_parent() method is considered legacy as of the 1.x series of SQLAlchemy and becomes a legacy construct in 2.0. Use the with_parent() standalone construct. (deprecated since: 2.0) (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)

Note that some warnings may be ignored through config in `setup.cfg`. Run `pytest -W all` to see all warnings.
