### ISSUE TITLE
Make it possible to run the graphql unit_tests with the entire suite

### ISSUE THREAD

**Issue by Mark90** [workfloworchestrator/orchestrator-core#393]
Currently you have to run the tests in a two-step approach like this

```
pytest test/unit_tests/ --ignore=test/unit_tests/graphql && pytest test/unit_tests/graphql
```

This is because of the autouse fixture `fastapi_app_graphql()` in `test/unit_tests/graphql/conftest.py` which attempts to register graphql models, which somehow causes strawberry to find duplicate models. I tried to dig into it a bit with a debugger but could not find the reason.

Would be great if we can make these tests run properly as part of the main suite.

**Comment by tjeerddie** [comment]
This gets fixed with my PR were the models are re-created with `register_graphql` and update the GraphQL schema with it.
https://github.com/workfloworchestrator/orchestrator-core/pull/440

**Comment by Mark90** [comment]
> This gets fixed with my PR were the models are re-created with `register_graphql` and update the GraphQL schema with it. #440

Awesome :)
