### ISSUE TITLE
[Feature]: Enforce that `TARGET` is set for all processes

### ISSUE THREAD

**Issue by wouter1975** [workfloworchestrator/orchestrator-core#406]
### What should we build?

It is possible that processes have no target set which is undesired. In most cases these processes should be set to TARGET = SYSTEM.

The allowed Targets are:
* create
* modify
* terminate
* system

### Proposal
- [ ] Enforce the Target being set at the workflow decorator.

**Comment by tjeerddie** [comment]
so target default should be `SYSTEM`
