### ISSUE TITLE
[IMPROVEMENT]: Update processTable to have a many to one relation with Workflow

### ISSUE THREAD

**Issue by tjeerddie** [workfloworchestrator/orchestrator-core#409]
### Contact Details

tjeerdverschragen@hotmail.com

### What should we build?

We want all processes to have a target, which with the current database structure will need quite some hacks. so instead of building ontop of the current structure, It would be better to change the database.

### Tasks
- [ ] Create a join between processes and workflows..
  - Multiple processes can have one workflow. (ProcessTable >---- WorkflowTable)
- [ ] Remove the `process_subscriptions.workflow_target` since it won't be necessary with the new relation.

**Comment by pboers1988** [comment]
fixed in https://github.com/workfloworchestrator/orchestrator-core/pull/433
