### ISSUE TITLE
[bug]: Graphql ProductBlockInstanceValues does not return all resource types

### ISSUE THREAD

**Issue by tjeerddie** [workfloworchestrator/orchestrator-core#414]
### What happened?

values like `UUID` are missing because there is a check that we only send values of type: `bool, str, int, float, type(None)`.

**Comment by wouter1975** [comment]
Please check VLANRANGE resource type as well, as it is also not shown.

**Comment by wouter1975** [comment]
Also routeservers IP addresses of the IP peer group product are not shown.

**Comment by hanstrompert** [comment]
Make this work also for list of primitive types.

**Comment by Mark90** [comment]
In the DomainModel we already have a way to distinguish productblock fields from non-productblock (i.e. resource type) fields. Ideally we reuse that here.

**Comment by pboers1988** [comment]
CLose Fix
