### ISSUE TITLE
[Feature]: Refactor Oauth2 handling

### ISSUE THREAD

**Issue by pboers1988** [workfloworchestrator/orchestrator-core#447]
### What should we build?

Refactor the OAUTH handling to make AuthN and AuthZ configurable on startup. Make sure they become non-mandatory configurable items as part of the OrchestratorApp class. 

This solution must include a configurable OIDCUser class and a pluggable opa_decision function.

**Comment by torkashvand** [comment]
related PRs are:

**oauth2-lib:** https://github.com/workfloworchestrator/oauth2-lib/pull/61

and 

**orchestrator-core:** https://github.com/workfloworchestrator/orchestrator-core/pull/608

**Comment by pboers1988** [comment]
done!
