### ISSUE TITLE
Refactor db filtering and sorting

### ISSUE THREAD

**Issue by tjeerddie** [workfloworchestrator/orchestrator-core#463]
- only process has camelcased and snakecased filtering with `BASE_CAMEL` and `BASE_SNAKE`. I believe we should improve it and add it to the other type filtering.
- we could check the column type and add filters for them automatically instead of needing to do it manually.
- I think this issue can be used to remove the `# TODO: will be removed in 1.4` fields.

**Comment by dmarjenburgh** [comment]
We should also unify the way we filter with `filter_by` and `query` parameters. They follow different code paths, but perform the same function.

Finally, there are generic inferred filters for the fields in a `BaseModel`, but we can extend it to work for related fields as well. E.g. we can search for product fields in a processes query.
