### ISSUE TITLE
[Feature]: Add high priority documentation for app.py

### ISSUE THREAD

**Issue by srichmond** [workfloworchestrator/orchestrator-core#529]
### Contact Details

srichmond@es.net

### What should we build?

Please create reference documentation for the following topics on https://workfloworchestrator.org/orchestrator-core/ using the "how to write docs" information located in https://docs.google.com/document/d/10Fz98moy-pMyyk__PTR8xg4aeHuIv5VegJa99ZpzvkI/edit

- [ ] App setup
- [ ] Generator

**Comment by pboers1988** [comment]
https://github.com/workfloworchestrator/orchestrator-core/blob/main/orchestrator/app.py

**Comment by hanstrompert** [comment]
Current generator documentation: https://workfloworchestrator.org/orchestrator-core/architecture/application/cli/#generate.
