### ISSUE TITLE
[Feature]: Add high priority documentation for Workflow Lifecyle transitioning

### ISSUE THREAD

**Issue by srichmond** [workfloworchestrator/orchestrator-core#532]
### Contact Details

srichmond@es.net

### What should we build?

Please create reference documentation for the following topics on https://workfloworchestrator.org/orchestrator-core/ using the "how to write docs" information located in https://docs.google.com/document/d/10Fz98moy-pMyyk__PTR8xg4aeHuIv5VegJa99ZpzvkI/edit

- [ ] Input Steps
- [ ] Callback Steps
- [ ] Waiting Steps
- [ ] Standard Steps
- [ ] Initial Input Form
- [ ] Inject Args - Type hinting and autocasting

**Comment by pboers1988** [comment]
https://workfloworchestrator.org/orchestrator-core/architecture/application/workflow/#default-workflows
