### ISSUE TITLE
[Feature]: Add high priority documentation for Database management

### ISSUE THREAD

**Issue by srichmond** [workfloworchestrator/orchestrator-core#540]
### Contact Details

srichmond@es.net

### What should we build?

Please create reference documentation for the following topics on https://workfloworchestrator.org/orchestrator-core/ using the "how to write docs" information located in https://docs.google.com/document/d/10Fz98moy-pMyyk__PTR8xg4aeHuIv5VegJa99ZpzvkI/edit

Schema Migrations
- [ ] Schema Migrations: Use the CLI tools
- [ ] Schema Migrations: Two “heads”

**Comment by pboers1988** [comment]
https://workfloworchestrator.org/orchestrator-core/getting-started/prepare-source-folder/#migrations-folder-and-local-alembic-head
