### ISSUE TITLE
[Feature]: Add high priority documentation for Domain Models

### ISSUE THREAD

**Issue by srichmond** [workfloworchestrator/orchestrator-core#543]
### Contact Details

srichmond@es.net

### What should we build?

Please create reference documentation for the following topics on https://workfloworchestrator.org/orchestrator-core/ using the "how to write docs" information located in https://docs.google.com/document/d/10Fz98moy-pMyyk__PTR8xg4aeHuIv5VegJa99ZpzvkI/edit

- [ ] Product Types
- [ ] Product Blocks
- [ ] Resource Types
- [ ] Product model generator - will generate all workflows, db migrations, test stubs and validations
- [ ] From_product
- [ ] From_subscription
- [ ] Validation
- [ ] Pydantic hooks
- [ ] Computed_property
- [ ] Title property
- [ ] Type-casting and serialisation
- [ ] Union types Most specific to least specific

**Comment by hanstrompert** [comment]
A lot of these topics are already, more or less, documented in either the orchestrator-core documentation and/or the example orchestrator documentation. Most of the work will probably exist of trying to merge both sets of documentation into one consistent piece of documentation. Also don't forget that slide decks that were used last year for presentations or workshops may also contain useful things like nice diagrams. After all existing documentation has been merged, the missing pieces can be added.

**Comment by hanstrompert** [comment]
And this document can also be of interest: GEANT 5-1 Milestone M7.3 Common NREN Network Service Product Models (https://resources.geant.org/wp-content/uploads/2023/06/M7.3_Common-NREN-Network-Service-Product-Models.pdf).
