### ISSUE TITLE
[Feature]: Add high priority documentation for Subscriptions

### ISSUE THREAD

**Issue by srichmond** [workfloworchestrator/orchestrator-core#545]
### Contact Details

srichmond@es.net

### What should we build?

Please create reference documentation for the following topics on https://workfloworchestrator.org/orchestrator-core/ using the "how to write docs" information located in https://docs.google.com/document/d/10Fz98moy-pMyyk__PTR8xg4aeHuIv5VegJa99ZpzvkI/edit

- [ ] Lifecycle of a Customer facing service
- [ ] Product-blocks are resource-facing
- [ ] Graph of all interlinked resources
- [ ] Depends_on
- [ ] In_use_by
- [ ] Customers need to be implemented as first class citizen

**Comment by pboers1988** [comment]
https://workfloworchestrator.org/orchestrator-core/architecture/application/graphql/?h=cu#overriding-customertype-and-resolvers Customers
