### ISSUE TITLE
[Feature]: Add low priority documentation for Auth(n|z)

### ISSUE THREAD

**Issue by srichmond** [workfloworchestrator/orchestrator-core#550]
### Contact Details

srichmond@es.net

### What should we build?

Please create reference documentation for the following topics on https://workfloworchestrator.org/orchestrator-core/ using the "how to write docs" information located in https://docs.google.com/document/d/10Fz98moy-pMyyk__PTR8xg4aeHuIv5VegJa99ZpzvkI/edit

- [ ] OIDCUser example
- [ ] Depends
- [ ] RBAC

**Comment by pboers1988** [comment]
Implemented
