### ISSUE TITLE
[Bug]: The orchestrator only responds with `Not Authorized` in the graphql response when handling an invalid access token

### ISSUE THREAD

**Issue by pboers1988** [workfloworchestrator/orchestrator-core#649]
### What happened?

Please introduce code to distinguish between not authenticated and not authorized to improve the error handling in the frontend applications.

### Version

2.2.0

### What python version are you seeing the problem on?

All

**Comment by Mark90** [comment]
I suggest to use `not_authenticated` as an error type.

Add this to the errorhandlerextension in nwa-stdlib, and then this PR should be updated to actually use it in orchestrator-core https://github.com/workfloworchestrator/orchestrator-core/pull/500

**Comment by pboers1988** [comment]
fixed

**Comment by Mark90** [comment]
Where/how was this fixed?
